------------------------------------------------------------------------
-- SPHelper  –  specs/Feral_Druid.lua
-- Feral Druid Cat DPS spec definition (TBC Anniversary).
--
-- Rotation outline:
--   1. Form safety and emergency Bear fallback.
--   2. Cat stealth opener and pre-pull Tiger's Fury.
--   3. Bear-form survival and dungeon/raid threat priorities.
--   4. Armor/debuff maintenance.
--   5. Finishers: Bite on kills/short TTD, Rip on sustainable targets, Bite again when Rip is healthy.
--   6. Bleed/debuff upkeep: Mangle then optional Rake.
--   7. Builder pair: Shred when ideal, Mangle as the paired fallback.
--   7. Powershift only when no builder/finisher is currently castable.
--
-- Notes:
--   • Rip snapshots AP — do NOT recast while still active (resets timer).
--   • Entries that share an explicitPriority bucket can crossfade the
--     primary icon automatically.
--   • The active default rotation is generated by SpecTemplates so every
--     entry remains editable/exportable through the rotation editor.
------------------------------------------------------------------------
local A = SPHelper

local spec = {
    _fromFile = true,

    meta = {
        id       = "feral_druid",
        class    = "DRUID",
        specName = "Feral Cat DPS",
        author   = "SPHelper",
        version  = 1,
    },

    loadConditions = {
        class    = "DRUID",
        talentTab = 2,           -- Feral talent tree (tab 2)
        -- Require Mangle (Cat) talent – tab 2, index ~16 in TBC layout:
        -- Mangle is a 41-pt talent in the Feral tree.
        -- The SpecValidator will only hard-fail if requiredTalents is set,
        -- so we use talentTab for detection and leave requiredTalents as
        -- an optional refinement (commented below).
        -- requiredTalents = {
        --     { tab = 2, index = 16, minRank = 1 },  -- Mangle (Cat) tier 8
        -- },
    },

    helpers = {
        "DotTracker",
        "Rotation",
        "RotationEngine",
        "SpecUI",
        "Config",
    },

    constants = {
        SAFETY = 0.5,
        timing = {
            globalWaitThresholdMs   = 200,
            defaultDelayToleranceMs = 400,
        },
    },

    trackedDebuffs = {
        { key = "rip",          spellKey = "Rip",          color = "SWP", isDot = true  },
        { key = "rake",         spellKey = "Rake",         color = "VT",  isDot = true  },
        { key = "mangle_cat",   spellKey = "Mangle (Cat)", source = "any", color = "MB",  isDot = false },  -- debuffAura/siblings resolved from SpellDatabase
        { key = "faerie_fire",  spellKey = "Faerie Fire (Feral)", source = "any", duration = 40, color = "FF", isDot = false },  -- debuffAura/siblings resolved from SpellDatabase
    },

    trackedBuffs = {
        { key = "clearcasting",    name = "Clearcasting",    spellKey = "Clearcasting" },
        { key = "cat_form",        name = "Cat Form",        spellKey = "Cat Form" },
        { key = "bear_form",       name = "Bear Form",       spellKey = "Bear Form" },
        { key = "dire_bear_form",  name = "Dire Bear Form",  spellKey = "Dire Bear Form" },
        { key = "stealth",         name = "Prowl",           spellKey = "Prowl" },
    },

    settingDefs = {
        use_rip                    = { type = "checkbox", label = "Use Rip",                default = true,
                                       tooltip = "Apply Rip as the primary sustained finisher when the target will live long enough." },
        use_mangle                 = { type = "checkbox", label = "Use Mangle",             default = true,
                                       tooltip = "Maintain Mangle debuff on target for the bleed-damage bonus." },
        use_shred                  = { type = "checkbox", label = "Use Shred",              default = true,
                                       tooltip = "Use Shred as primary combo-point generator." },
        use_rake                   = { type = "checkbox", label = "Use Rake",               default = true,
                                       tooltip = "Maintain Rake on targets that will live long enough; this also keeps a bleed active before Rip is up." },
        fade_primary_icon          = { type = "checkbox", label = "Fade primary icon",      default = true,
                                       tooltip = "Crossfade the top two ready recommendations when they share the same explicitPriority bucket." },
        use_faerie_fire            = { type = "checkbox", label = "Use Faerie Fire",        default = true,
                                       tooltip = "Maintain Faerie Fire (Feral) when the armor debuff is missing or about to expire." },
        faerie_fire_refresh_seconds= { type = "slider",   label = "Faerie Fire refresh window",  default = 2, min = 1, max = 6, step = 1,
                                       tooltip = "Refresh Faerie Fire when any armor-reduction debuff copy has this many seconds or less remaining." },
        use_ferocious_bite         = { type = "checkbox", label = "Use Ferocious Bite",     default = true,
                                       tooltip = "Use Ferocious Bite when target is dying fast or for trash/execute." },
        use_tigers_fury            = { type = "checkbox", label = "Use Tiger's Fury",       default = true,
                                       tooltip = "Use Tiger's Fury as a pre-pull opener when starting out of stealth and at full energy." },
        use_powershift             = { type = "checkbox", label = "Suggest powershift",     default = true,
                                       tooltip = "Suggest Cat Form again when energy is low enough to justify a powershift." },
        powershift_min_mana_pct    = { type = "slider",   label = "Powershift minimum mana %",   default = 20, min = 0, max = 100, step = 1,
                                       tooltip = "Only suggest powershift when the player's mana bar is above this percentage of max mana. Set to 0 to allow powershifting at any mana level." },
        use_bear_form              = { type = "checkbox", label = "Emergency Bear Form",    default = true,
                                       tooltip = "Suggest Bear Form when health drops below the bear threshold." },
        bear_form_hp_pct           = { type = "slider",   label = "Bear Form health threshold",   default = 35, min = 5, max = 100, step = 1,
                                       tooltip = "Switch to Bear Form when player health drops below this percentage." },
        bear_fr_hp_pct             = { type = "slider",   label = "Frenzied Regen health threshold", default = 55, min = 10, max = 100, step = 1,
                                       tooltip = "Use Frenzied Regeneration when in Bear Form and health drops below this percentage." },
        rip_min_cp                 = { type = "slider",   label = "Rip minimum combo points",    default = 4, min = 3, max = 5, step = 1,
                                       tooltip = "Minimum combo points required before applying Rip." },
        rip_min_ttd                = { type = "slider",   label = "Rip minimum target TTD",      default = 10, min = 0, max = 20, step = 1,
                                       tooltip = "Only suggest Rip when the target is expected to live at least this many seconds. 0 = disabled." },
        rake_min_ttd               = { type = "slider",   label = "Rake minimum target TTD",     default = 9, min = 0, max = 20, step = 1,
                                       tooltip = "Only suggest Rake when the target is expected to live long enough for most of the bleed." },
        ferocious_bite_min_rip_remaining = { type = "slider", label = "Bite minimum Rip remaining", default = 6, min = 0, max = 12, step = 1,
                                       tooltip = "At 5 combo points, use Ferocious Bite when Rip has at least this many seconds left." },
        mangle_refresh_seconds     = { type = "slider",   label = "Mangle refresh window",       default = 2, min = 1, max = 6, step = 1,
                                       tooltip = "Refresh Mangle when the debuff has this many seconds or less remaining." },
        dying_fast_pct             = { type = "slider",   label = "Dying fast threshold (%HP/sec)", default = 5, min = 1, max = 20, step = 1,
                                       tooltip = "(Legacy – no longer used in rotation; kept for saved-data compatibility.)" },
        ferocious_bite_hp_threshold= { type = "slider",   label = "Ferocious Bite HP threshold (absolute)", default = 0, min = 0, max = 100000, step = 1,
                                       tooltip = "(Legacy – no longer used in rotation; kept for saved-data compatibility.)" },
    },

    -- Settings consumed by engine/display logic that aren't directly
    -- referenced in rotation conditions via optionKey / string value fields.
    generalSettings = {
        "fade_primary_icon",  -- controls icon crossfade in the preview display
    },

    castBarOptions = {},

    channelSpells = {},

    -- ---------------------------------------------------------------
    -- Rotation (ordered priority list)
    -- Each entry is evaluated top-to-bottom; the first entry where ALL
    -- conditions pass becomes the suggested spell.
    -- ---------------------------------------------------------------
    legacyRotation = {
        -- Emergency Bear Form fallback when health drops and the mode is enabled.
        {
            conditions = {
                { type = "spec_option_enabled", optionKey = "use_bear_form" },
                { type = "state_compare",       subject = "player_hp_pct", op = "<", value = "bear_form_hp_pct" },
                { type = "not", condition = { type = "bear_form" } },
            },
        },

        -- ── Ensure Cat Form ───────────────────────────────────────
        -- Suggest Cat Form when the player is not currently in Cat Form.
        {
            key        = "Cat Form",
            conditions = {
                { type = "buff_property_compare", buff = "Cat Form", property = "stacks", op = "==", value = 0 },
                { type = "any_of", conditions = {
                    { type = "not", condition = { type = "spec_option_enabled", optionKey = "use_bear_form" } },
                    { type = "state_compare", subject = "player_hp_pct", op = ">", value = "bear_form_hp_pct" },
                }},
                { type = "not", condition = { type = "bear_form" } },
            },
        },

        -- ── BEAR FORM ────────────────────────────────────────────
        -- When already in bear form, keep the suggestions on self-sustain for solo play or on threat tools for dungeon/raid tanking.
        {
            key        = "Frenzied Regeneration",
            conditions = {
                { type = "bear_form" },
                { type = "state_compare", subject = "player_hp_pct", op = "<", value = "bear_fr_hp_pct" },
                { type = "resource_gte", amount = 10 },
            },
        },

        {
            key        = "Bash",
            conditions = {
                { type = "bear_form" },
                { type = "target_valid" },
                { type = "resource_gte", amount = 10 },
                { type = "unit_cast_compare", unit = "target", op = ">", value = 0 },
                { type = "unit_interruptible", unit = "target" },
            },
        },

        {
            key        = "Demoralizing Roar",
            conditions = {
                { type = "bear_form" },
                { type = "target_valid" },
                { type = "resource_gte", amount = 10 },
                { type = "debuff_property_compare", debuff = "Demoralizing Roar", source = "any", property = "remaining", op = "<", value = 4 },
            },
        },

        {
            key        = "Faerie Fire (Feral)",
            conditions = {
                { type = "bear_form" },
                { type = "target_valid" },
                { type = "cooldown_ready", spellKey = "Faerie Fire (Feral)" },
                { type = "debuff_property_compare", spellKey = "Faerie Fire (Feral)", source = "any", property = "remaining", op = "<", value = "faerie_fire_refresh_seconds" },
            },
        },

        {
            key        = "Mangle (Bear)",
            conditions = {
                { type = "bear_form" },
                { type = "target_valid" },
                { type = "cooldown_ready", spellKey = "Mangle (Bear)" },
                { type = "resource_gte", amount = 20 },
            },
        },

        {
            key        = "Lacerate",
            conditions = {
                { type = "bear_form" },
                { type = "target_valid" },
                { type = "any_of", conditions = {
                    { type = "debuff_property_compare", debuff = "Lacerate", source = "player", property = "stacks", op = "<", value = 5 },
                    { type = "debuff_property_compare", debuff = "Lacerate", source = "player", property = "remaining", op = "<", value = 4 },
                }},
                { type = "any_of", conditions = {
                    { type = "content_type", contentType = "dungeon" },
                    { type = "content_type", contentType = "raid" },
                }},
                { type = "resource_gte", amount = 15 },
            },
        },

        {
            key        = "Swipe",
            conditions = {
                { type = "bear_form" },
                { type = "target_valid" },
                { type = "any_of", conditions = {
                    { type = "content_type", contentType = "dungeon" },
                    { type = "content_type", contentType = "raid" },
                }},
                { type = "resource_gte", amount = 30 },
            },
        },

        {
            key        = "Maul",
            conditions = {
                { type = "bear_form" },
                { type = "target_valid" },
                { type = "resource_gte", amount = 50 },
            },
        },

        -- ── PRE-PULL / MAINTENANCE ────────────────────────────────
        -- Pre-pull Tiger's Fury when starting visible and energy-capped.
        {
            key        = "Tiger's Fury",
            conditions = {
                { type = "spec_option_enabled", optionKey = "use_tigers_fury" },
                { type = "cat_form" },
                { type = "precombat" },
                { type = "not_stealthed" },
                { type = "resource_required_gte",        amount = 100 },
                { type = "cooldown_ready",      spellKey  = "Tiger's Fury" },
            },
        },

        -- 2. Ravage – stealth opener when behind target (costs 60 energy)
        {
            key        = "Ravage",
            explicitPriority = 200,
            conditions = {
                { type = "cat_form" },
                { type = "target_valid" },
                { type = "precombat" },
                { type = "is_stealthed" },
                { type = "behind_target" },
                { type = "resource_gte", amount = 60 },
            },
        },

        -- 3. Pounce – stealth opener when not behind target (costs 50 energy)
        {
            key        = "Pounce",
            explicitPriority = 200,
            conditions = {
                { type = "cat_form" },
                { type = "target_valid" },
                { type = "precombat" },
                { type = "is_stealthed" },
                { type = "not_behind_target" },
                { type = "resource_gte", amount = 50 },
            },
        },

        -- Maintain Faerie Fire using any-source debuff timing so we do not reapply over another druid's copy.
        {
            key        = "Faerie Fire (Feral)",
            conditions = {
                { type = "spec_option_enabled", optionKey = "use_faerie_fire" },
                { type = "cat_form" },
                { type = "not_stealthed" },
                { type = "target_valid" },
                { type = "cooldown_ready", spellKey = "Faerie Fire (Feral)" },
                { type = "debuff_property_compare", spellKey = "Faerie Fire (Feral)", source = "any", property = "remaining", op = "<", value = "faerie_fire_refresh_seconds" },
            },
        },

        -- ── FINISHERS ─────────────────────────────────────────────
        -- Ferocious Bite at 5 CP when:
        --   a) target TTD is shorter than rip_min_ttd (not worth applying Rip), OR
        --   b) the estimated hit will outright kill the target.
        -- At 5 CP we always go for it in either case.
        {
            key        = "Ferocious Bite",
            conditions = {
                { type = "cat_form" },
                { type = "target_valid" },
                { type = "not_stealthed" },
                { type = "spec_option_enabled", optionKey = "use_ferocious_bite" },
                { type = "state_compare", subject = "combo_points", op = ">=", value = 5 },
                { type = "any_of", conditions = {
                    { type = "state_compare", subject = "resource", op = ">=", value = 35 },
                    { type = "clearcasting" },
                }},
                -- Target dying too fast for Rip to tick out, OR FB will kill it outright.
                { type = "any_of", conditions = {
                    { type = "state_compare", subject = "target_ttd", op = "<", value = "rip_min_ttd" },
                    { type = "spell_can_kill_target", spellKey = "Ferocious Bite" },
                }},
            },
        },

        -- Ferocious Bite at 4 CP — only when FB is predicted to kill the target.
        -- (If target is dying fast but FB can't kill at 4 CP, fall through to Shred/Mangle.)
        {
            key        = "Ferocious Bite",
            conditions = {
                { type = "cat_form" },
                { type = "target_valid" },
                { type = "not_stealthed" },
                { type = "spec_option_enabled", optionKey = "use_ferocious_bite" },
                { type = "state_compare", subject = "combo_points", op = ">=", value = 4 },
                { type = "any_of", conditions = {
                    { type = "state_compare", subject = "resource", op = ">=", value = 35 },
                    { type = "clearcasting" },
                }},
                { type = "spell_can_kill_target", spellKey = "Ferocious Bite" },
            },
        },

        -- Rip on targets that will live long enough to justify it. Never clip; suppress immediate re-suggest after a cast.
        {
            key        = "Rip",
            conditions = {
                { type = "cat_form" },
                { type = "target_valid" },
                { type = "spec_option_enabled", optionKey = "use_rip" },
                { type = "not_stealthed" },
                { type = "state_compare", subject = "combo_points", op = ">=", value = "rip_min_cp" },
                { type = "state_compare", subject = "target_ttd", op = ">=", value = "rip_min_ttd" },
                { type = "any_of", conditions = {
                    { type = "state_compare", subject = "resource", op = ">=", value = 30 },
                    { type = "clearcasting" },
                }},
                { type = "not_recently_cast", spellKey = "Rip", window = 0.6 },
                { type = "dot_missing",         spellKey  = "Rip" },
            },
        },

        -- Refresh Mangle before dropping the debuff.
        {
            key        = "Mangle (Cat)",
            explicitPriority = 10,  -- same bucket as builders so crossfade works when refresh fires
            conditions = {
                { type = "cat_form" },
                { type = "target_valid" },
                { type = "spec_option_enabled", optionKey = "use_mangle" },
                { type = "not_stealthed" },
                { type = "debuff_property_compare", spellKey = "Mangle (Cat)", source = "any", property = "remaining", op = "<", value = "mangle_refresh_seconds" },
                { type = "any_of", conditions = {
                    { type = "state_compare", subject = "resource", op = ">=", value = 40 },
                    { type = "clearcasting" },
                }},
            },
        },

        -- ── BUILDERS ──────────────────────────────────────────────
        -- Aggro-gated split: Shred when target is NOT attacking the player
        -- (player can safely position behind); Mangle when player has aggro
        -- (target is facing the player, Shred can't be used from the front)
        -- or when Shred is disabled.  The two entries are mutually exclusive
        -- so the fade animation is never needed for this pair.
        {
            key        = "Shred",
            explicitPriority = 10,
            conditions = {
                { type = "cat_form" },
                { type = "target_valid" },
                { type = "spec_option_enabled", optionKey = "use_shred" },
                { type = "not_stealthed" },
                -- Only suggest Shred when target is not attacking the player,
                -- since that means the player can safely position behind it.
                { type = "not_has_aggro" },
                { type = "any_of", conditions = {
                    { type = "state_compare", subject = "resource", op = ">=", value = 42 },
                    { type = "clearcasting" },
                }},
            },
        },

        {
            key        = "Mangle (Cat)",
            explicitPriority = 10,
            conditions = {
                { type = "cat_form" },
                { type = "target_valid" },
                { type = "spec_option_enabled", optionKey = "use_mangle" },
                { type = "not_stealthed" },
                -- Suggest Mangle when the target is attacking the player (can't
                -- Shred from the front), or when Shred is disabled entirely.
                { type = "any_of", conditions = {
                    { type = "has_aggro" },
                    { type = "not", condition = { type = "spec_option_enabled", optionKey = "use_shred" } },
                }},
                { type = "any_of", conditions = {
                    { type = "state_compare", subject = "resource", op = ">=", value = 40 },
                    { type = "clearcasting" },
                }},
            },
        },

        -- Powershift only when we are still in Cat Form, have mana to spare, and do not currently have a free cast.
        {
            key        = "Cat Form",
            -- After powershifting we re-enter Cat Form with energy refunded
            -- by Furor (and optionally +20 from Wolfshead Helm). Declare it
            -- so the engine projects the post-shift resource state into the
            -- queue ETAs (Shred / Mangle then show "ready in <gcd>" rather
            -- than "wait N seconds for energy regen").
            postCast   = { resource = "energy", compute = "ComputePowershiftEnergy" },
            conditions = {
                { type = "cat_form" },
                { type = "not_stealthed" },
                { type = "spec_option_enabled", optionKey = "use_powershift" },
                { type = "in_combat" },
                -- Use player_mana_pct (current / max mana, matching the UI mana bar)
                -- so the threshold slider matches what the player sees.
                -- The check prevents powershifting when mana is below the configured
                -- minimum, which would leave too little mana to re-cast Cat Form.
                { type = "state_compare", subject = "player_mana_pct", op = ">", value = "powershift_min_mana_pct" },
                { type = "not", condition = { type = "clearcasting" } },
                -- Only suggest powershift when current energy is low enough that
                -- even after ONE energy tick the player still wouldn't have enough
                -- to cast the next ability.  This means the player would have to
                -- wait for at least 2 ticks — at which point powershifting is
                -- faster than standing still.
                --
                -- Threshold = ability_cost - energy_per_tick (20):
                --   Has aggro  → Mangle (40 cost) → threshold 20  (40 - 20)
                --   No aggro   → Shred  (42 cost) → threshold 22  (42 - 20)
                { type = "any_of", conditions = {
                    { type = "all_of", conditions = {
                        { type = "has_aggro" },
                        { type = "state_compare", subject = "resource", op = "<", value = 20 },
                    }},
                    { type = "all_of", conditions = {
                        { type = "not_has_aggro" },
                        { type = "state_compare", subject = "resource", op = "<", value = 22 },
                    }},
                }},
            },
        },

    },  -- end rotation
}

spec.rotation = A.SpecTemplates.BuildFeralDruidRotation(spec)

------------------------------------------------------------------------
-- Register
------------------------------------------------------------------------
if A.SpecManager then
    A.SpecManager:RegisterSpec(spec)
end
