local A = SPHelper
local T = A.SpecTemplates

local spec = {
    _fromFile = true,
    meta = { id = "arcane_mage", class = "MAGE", specName = "Arcane", author = "SPHelper", version = 1 },
    loadConditions = { class = "MAGE", talentTab = 1 },
    helpers = { "CastBar", "Rotation", "RotationEngine", "SpellData", "SpecUI", "Config" },
    constants = { SAFETY = 0.5, timing = { globalWaitThresholdMs = 400, defaultDelayToleranceMs = 600, dotSafeWindowSec = 1.5 } },
    settingDefs = {
        use_arcane_power = { type = "checkbox", label = "Use Arcane Power", default = true, tooltip = "Use Arcane Power on cooldown." },
        arcane_power_classification = { type = "dropdown", label = "Arcane Power target type", default = "any",
                                      tooltip = "Restrict Arcane Power to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
        use_presence_of_mind = { type = "checkbox", label = "Use Presence of Mind", default = true, tooltip = "Use Presence of Mind on cooldown." },
        presence_of_mind_classification = { type = "dropdown", label = "Presence of Mind target type", default = "any",
                                      tooltip = "Restrict Presence of Mind to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
        use_evocation = { type = "checkbox", label = "Use Evocation", default = true, tooltip = "Use Evocation when low on mana." },
        evocation_classification = { type = "dropdown", label = "Evocation target type", default = "any",
                                      tooltip = "Restrict Evocation to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
        evocationManaPct = { type = "slider", label = "Evocation mana %", default = 20, min = 5, max = 80, step = 5, tooltip = "Evocation when mana below this %." },
        suggestPot = { type = "checkbox", label = "Suggest mana potion", default = true, tooltip = "Show mana potion suggestion." },
        potManaThreshold = { type = "slider", label = "Potion mana %", default = 10, min = 5, max = 100, step = 5, tooltip = "Potion when mana below this %." },
        suggestRune = { type = "checkbox", label = "Suggest dark rune", default = true, tooltip = "Show rune suggestion." },
        runeManaThreshold = { type = "slider", label = "Rune mana %", default = 10, min = 5, max = 100, step = 5, tooltip = "Rune when mana below this %." },
        use_icy_veins = { type = "checkbox", label = "Use Icy Veins", default = true, tooltip = "Use Icy Veins on cooldown (40/21 Arcane/Frost build)." },
        icy_veins_classification = { type = "dropdown", label = "Icy Veins target type", default = "any",
                                      tooltip = "Restrict Icy Veins to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
        use_cold_snap = { type = "checkbox", label = "Use Cold Snap", default = true, tooltip = "Use Cold Snap to reset Icy Veins cooldown." },
        cold_snap_classification = { type = "dropdown", label = "Cold Snap target type", default = "any",
                                      tooltip = "Restrict Cold Snap to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
        use_fire_blast = { type = "checkbox", label = "Use Fire Blast (movement)", default = true, tooltip = "Fire Blast as instant-cast movement filler." },
        use_mana_sapphire = { type = "checkbox", label = "Use Mana Sapphire", default = true, tooltip = "Use conjured Mana Sapphire for mana recovery." },
        manaGemManaPct = { type = "slider", label = "Mana gem mana %", default = 50, min = 5, max = 100, step = 5, tooltip = "Suggest Mana Sapphire when mana drops below this percentage." },
        use_trinket_1            = { type = "checkbox", label = "Use trinket 1 (on-use)",  default = true,
                                      tooltip = "Activate trinket 1 on cooldown automatically." },
        use_trinket_2            = { type = "checkbox", label = "Use trinket 2 (on-use)",  default = true,
                                      tooltip = "Activate trinket 2 on cooldown automatically." },
        trinket_1_classification = { type = "dropdown", label = "Trinket 1 target type",   default = "any",
                                      tooltip = "Restrict trinket 1 to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
        trinket_2_classification = { type = "dropdown", label = "Trinket 2 target type",   default = "any",
                                      tooltip = "Restrict trinket 2 to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
    },
    settingOrder = { "use_arcane_power", "arcane_power_classification", "use_presence_of_mind", "presence_of_mind_classification", "use_evocation", "evocation_classification", "evocationManaPct", "suggestPot", "potManaThreshold", "suggestRune", "runeManaThreshold", "use_icy_veins", "icy_veins_classification", "use_cold_snap", "cold_snap_classification", "use_fire_blast", "use_mana_sapphire", "manaGemManaPct", "use_trinket_1", "trinket_1_classification", "use_trinket_2", "trinket_2_classification" },
    trackedBuffs = {
        { key = "icy_veins", name = "Icy Veins", spellKey = "Icy Veins" },
    },
    rotation = T.BuildArcaneMageRotation and T.BuildArcaneMageRotation(spec),
}

if A.SpecManager then A.SpecManager:RegisterSpec(spec) end
