local A = SPHelper
local T = A.SpecTemplates

local spec = {
    _fromFile = true,
    meta = { id = "retribution_paladin", class = "PALADIN", specName = "Retribution", author = "SPHelper", version = 1 },
    loadConditions = { class = "PALADIN", talentTab = 3 },
    helpers = { "CastBar", "Rotation", "RotationEngine", "SpellData", "SpecUI", "Config" },
    constants = { SAFETY = 0.5, timing = { globalWaitThresholdMs = 200, defaultDelayToleranceMs = 400, dotSafeWindowSec = 1.0 } },
    trackedDebuffs = {
        { key = "judgement_wisdom", spellKey = "Judgement of Wisdom", color = "MB", isDot = false },
        { key = "judgement_light", spellKey = "Judgement of Light", color = "MB", isDot = false },
    },
    trackedBuffs = {
        { key = "seal_of_blood", name = "Seal of Blood", spellKey = "Seal of Blood" },
        { key = "seal_of_vengeance", name = "Seal of Vengeance", spellKey = "Seal of Vengeance" },
        { key = "divine_plea", name = "Divine Plea", spellKey = "Divine Plea" },
        { key = "avenging_wrath", name = "Avenging Wrath", spellKey = "Avenging Wrath" },
        { key = "righteous_fury", name = "Righteous Fury", spellKey = "Righteous Fury" },
        { key = "crusader_seal", name = "Seal of the Crusader", spellKey = "Seal of the Crusader" },
        { key = "command_seal", name = "Seal of Command", spellKey = "Seal of Command" },
        { key = "judgement_crusader", name = "Judgement of the Crusader", spellKey = "Judgement of the Crusader", source = "any" },
    },
    settingDefs = {
        use_avenging_wrath = { type = "checkbox", label = "Use Avenging Wrath", default = true, tooltip = "Avenging Wrath on cooldown." },
        avenging_wrath_classification = { type = "dropdown", label = "Avenging Wrath target type", default = "any",
                                      tooltip = "Restrict Avenging Wrath to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
        use_seal_of_blood = { type = "checkbox", label = "Use Seal of Blood", default = true, tooltip = "Maintain Seal of Blood (or appropriate seal)." },
        use_crusader_strike = { type = "checkbox", label = "Use Crusader Strike", default = true, tooltip = "Crusader Strike on cooldown." },
        use_consecration = { type = "checkbox", label = "Use Consecration", default = true, tooltip = "Consecration on cooldown." },
        use_holy_wrath = { type = "checkbox", label = "Use Holy Wrath", default = true, tooltip = "Holy Wrath on cooldown." },
        use_exorcism = { type = "checkbox", label = "Use Exorcism (Undead/Demon)", default = true, tooltip = "Exorcism on Undead targets." },
        use_hammer_of_wrath = { type = "checkbox", label = "Use Hammer of Wrath", default = true, tooltip = "Hammer of Wrath on execute." },
        use_judgement_wisdom = { type = "checkbox", label = "Use Judgement of Wisdom", default = true, tooltip = "Apply Judgement of Wisdom for mana regen." },
        use_divine_plea = { type = "checkbox", label = "Use Divine Plea", default = true, tooltip = "Divine Plea on cooldown." },
        use_righteous_fury = { type = "checkbox", label = "Use Righteous Fury (pull)", default = true, tooltip = "Righteous Fury for threat generation." },
        use_crusader_seal = { type = "checkbox", label = "Use Seal of the Crusader", default = true, tooltip = "Apply Judgement of the Crusader debuff for +3% holy damage." },
        use_seal_twisting = { type = "checkbox", label = "Seal Twisting (SoC)", default = true, tooltip = "Seal twist Seal of Command before each swing for bonus damage." },
        sealTwistSwingLead = { type = "slider", label = "Twist lead (seconds)", default = 1.6, min = 1.0, max = 2.5, step = 0.1, tooltip = "Swing time remaining threshold to begin the twist." },
        sealTwistSwingReturn = { type = "slider", label = "Twist return (seconds)", default = 0.4, min = 0.1, max = 1.0, step = 0.1, tooltip = "Swing time remaining threshold to return to main seal." },
        suggestPot        = { type = "checkbox", label = "Suggest mana potion",    default = true,
                              tooltip = "Show mana potion in rotation suggestions when low on mana." },
        potManaThreshold  = { type = "slider",   label = "Potion mana %",         default = 10, min = 5, max = 100, step = 5,
                              tooltip = "Suggest mana potion when mana drops below this percentage." },
        suggestRune       = { type = "checkbox", label = "Suggest dark rune",      default = true,
                              tooltip = "Show dark/demonic rune in rotation suggestions when low on mana." },
        runeManaThreshold = { type = "slider",   label = "Rune mana %",           default = 10, min = 5, max = 100, step = 5,
                              tooltip = "Suggest rune when mana drops below this percentage." },
        use_trinket_1            = { type = "checkbox", label = "Use trinket 1 (on-use)",  default = true,
                                      tooltip = "Activate trinket 1 on cooldown automatically." },
        use_trinket_2            = { type = "checkbox", label = "Use trinket 2 (on-use)",  default = true,
                                      tooltip = "Activate trinket 2 on cooldown automatically." },
        trinket_1_classification = { type = "dropdown", label = "Trinket 1 target type",   default = "any",
                                      tooltip = "Restrict trinket 1 to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
        trinket_2_classification = { type = "dropdown", label = "Trinket 2 target type",   default = "any",
                                      tooltip = "Restrict trinket 2 to: any, normal, elite, or boss.",
                                      values = { "any", "normal", "elite", "boss" } },
    },
    settingOrder = { "use_avenging_wrath", "avenging_wrath_classification", "use_seal_of_blood", "use_crusader_strike", "use_consecration", "use_holy_wrath", "use_exorcism", "use_hammer_of_wrath", "use_judgement_wisdom", "use_divine_plea", "use_righteous_fury", "use_crusader_seal", "use_seal_twisting", "sealTwistSwingLead", "sealTwistSwingReturn", "suggestPot", "potManaThreshold", "suggestRune", "runeManaThreshold", "use_trinket_1", "trinket_1_classification", "use_trinket_2", "trinket_2_classification" },
    rotation = T.BuildRetributionPaladinRotation and T.BuildRetributionPaladinRotation(spec),
}

if A.SpecManager then A.SpecManager:RegisterSpec(spec) end
